POST http://localhost:3000/card
Content-Type: application/json

{
  "name": "Warrior Name",
  "description": "Draw 2 cards",
  "imageURL": "dragon.jpg",
  "class": "Warrior",
  "victoryRoll": 4,
  "effects": ["Draw;2;self"]
}


### Post Magic
POST http://localhost:3000/card
Content-Type: application/json

{
  "name": "Magic Name",
  "description": "Draw 2 cards",
  "imageURL": "magic.jpg",
  "effects": ["Draw;2;self"]
}

### Post Challenge
POST http://localhost:3000/card
Content-Type: application/json

{
  "name": "Challenge Name",
  "description": "Normal challenge",
  "imageURL": "default_challenge.jpg",
  "modifier": 0
}

### Post Monster
POST http://localhost:3000/card
Content-Type: application/json

{
  "name": "Monster Name",
  "description": "Big Bad Monster",
  "imageURL": "dragon.jpg",
  "victoryRoll": 4,
  "defeatRoll": 9,
  "effects": ["Draw;enemy;1"]
}


### 
GET http://localhost:3000/card